### PR TITLE
Allow GHC 8.10 + 9.0 and bytestring 0.11

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by sjakobi** [comment]
Ping @byorgey! :)

**Comment by byorgey** [comment]
Thanks for the ping!  I plan to get to this soon, once the semester is over.

**Comment by bravit** [comment]
Hi @byorgey, sorry for another ping!

**Comment by chris-martin** [comment]
Thanks! I'm using this patch.

**Comment by Hazelfire** [comment]
Would love this merged!

**Comment by sjakobi** [comment]
Ping @byorgey! :)

Since I'm getting a clean build with GHC-9.0.1 and `--allow-newer='hashable:base'`, I've bumped the `base` bound to `< 4.16`.

**Comment by sjakobi** [comment]
As a Hackage Trustee, I have created a Hackage revision corresponding to this PR: http://hackage.haskell.org/package/svg-builder-0.1.1/revisions/

**Pull request merged**
